--
-- PostgreSQL database dump
--

\restrict u9vh52NFMlhXUqWIE006EOsvFqGhpGU23DDV7Lyg7sckDU2O9EFZLhdsMqRT7xv

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_audit_logs (
    id bigint NOT NULL,
    admin_user_id bigint NOT NULL,
    action character varying(80) NOT NULL,
    target_type character varying(40) NOT NULL,
    target_id character varying(120) NOT NULL,
    summary character varying(300),
    before_json jsonb,
    after_json jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: admin_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: auth_refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_refresh_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    refresh_token_hash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    revoked_at timestamp without time zone
);


--
-- Name: auth_refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.auth_refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: auth_refresh_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.auth_refresh_tokens_id_seq OWNED BY public.auth_refresh_tokens.id;


--
-- Name: eligible_island_catalog_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eligible_island_catalog_snapshots (
    id bigint NOT NULL,
    catalog_id bigint NOT NULL,
    notice_url character varying(500),
    notice_title character varying(300),
    attachment_url character varying(500),
    attachment_filename character varying(255),
    attachment_fingerprint character varying(64),
    attachment_documents jsonb DEFAULT '[]'::jsonb NOT NULL,
    parser_version character varying(40) DEFAULT 'v1'::character varying NOT NULL,
    fetched_at timestamp without time zone DEFAULT now() NOT NULL,
    entry_count integer DEFAULT 0 NOT NULL,
    added_count integer DEFAULT 0 NOT NULL,
    removed_count integer DEFAULT 0 NOT NULL,
    changed_count integer DEFAULT 0 NOT NULL,
    review_status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    reviewed_by_user_id bigint,
    reviewed_at timestamp without time zone,
    review_note text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_eligible_island_catalog_snapshots_review_status CHECK (((review_status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'superseded'::character varying])::text[])))
);


--
-- Name: eligible_island_catalog_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.eligible_island_catalog_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: eligible_island_catalog_snapshots_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.eligible_island_catalog_snapshots_id_seq OWNED BY public.eligible_island_catalog_snapshots.id;


--
-- Name: eligible_island_catalogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eligible_island_catalogs (
    id bigint NOT NULL,
    key character varying(80) NOT NULL,
    display_name character varying(120) NOT NULL,
    notice_list_url character varying(500) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    approved_snapshot_id bigint,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: eligible_island_catalogs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.eligible_island_catalogs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: eligible_island_catalogs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.eligible_island_catalogs_id_seq OWNED BY public.eligible_island_catalogs.id;


--
-- Name: eligible_island_snapshot_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eligible_island_snapshot_entries (
    id bigint NOT NULL,
    snapshot_id bigint NOT NULL,
    display_name character varying(120) NOT NULL,
    normalized_name character varying(120) NOT NULL,
    jurisdiction_name character varying(120) NOT NULL,
    raw_region_text character varying(300),
    row_fingerprint character varying(64) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: eligible_island_snapshot_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.eligible_island_snapshot_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: eligible_island_snapshot_entries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.eligible_island_snapshot_entries_id_seq OWNED BY public.eligible_island_snapshot_entries.id;


--
-- Name: eligible_islands; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.eligible_islands (
    id bigint NOT NULL,
    catalog_id bigint NOT NULL,
    snapshot_id bigint NOT NULL,
    display_name character varying(120) NOT NULL,
    normalized_name character varying(120) NOT NULL,
    jurisdiction_name character varying(120) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: eligible_islands_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.eligible_islands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: eligible_islands_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.eligible_islands_id_seq OWNED BY public.eligible_islands.id;


--
-- Name: external_source_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.external_source_records (
    id bigint NOT NULL,
    source_name character varying(100) NOT NULL,
    source_type character varying(50) NOT NULL,
    source_url character varying(500) NOT NULL,
    source_category character varying(80) NOT NULL,
    external_id character varying(160) NOT NULL,
    canonical_key character varying(160) NOT NULL,
    detail_url character varying(500),
    collected_page_url character varying(500) NOT NULL,
    title character varying(300) NOT NULL,
    organizer_text character varying(300) NOT NULL,
    organizers jsonb NOT NULL,
    region character varying(50),
    city character varying(80),
    is_nationwide boolean DEFAULT false NOT NULL,
    status_text text,
    status character varying(30) NOT NULL,
    start_date date,
    end_date date,
    benefit_text text NOT NULL,
    benefit_value_text character varying(300),
    extracted_amount_krw integer,
    extracted_discount_percent integer,
    benefit_value_type character varying(30) NOT NULL,
    tags jsonb NOT NULL,
    contact_text character varying(200),
    inferred_travel_styles jsonb NOT NULL,
    confidence integer NOT NULL,
    field_completeness integer NOT NULL,
    raw_list_text text NOT NULL,
    raw_detail_text text NOT NULL,
    raw_payload jsonb NOT NULL,
    last_fetched_at timestamp without time zone NOT NULL,
    last_verified_at timestamp without time zone,
    freshness_status character varying(30) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    logical_key character varying(200),
    canonical_key_version character varying(30)
);


--
-- Name: external_source_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.external_source_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: external_source_records_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.external_source_records_id_seq OWNED BY public.external_source_records.id;


--
-- Name: notification_deliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_deliveries (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    policy_id bigint NOT NULL,
    channel character varying(30) NOT NULL,
    lead_day integer NOT NULL,
    target_deadline_date date NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    provider_message_id character varying(100),
    error_message text,
    scheduled_at timestamp without time zone,
    sent_at timestamp without time zone,
    failed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: notification_deliveries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notification_deliveries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notification_deliveries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notification_deliveries_id_seq OWNED BY public.notification_deliveries.id;


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.password_reset_tokens_id_seq OWNED BY public.password_reset_tokens.id;


--
-- Name: pending_signups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pending_signups (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    token_hash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    terms_accepted boolean DEFAULT false NOT NULL,
    terms_accepted_at timestamp without time zone,
    terms_version character varying(32),
    privacy_accepted boolean DEFAULT false NOT NULL,
    privacy_accepted_at timestamp without time zone,
    privacy_version character varying(32)
);


--
-- Name: pending_signups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pending_signups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pending_signups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pending_signups_id_seq OWNED BY public.pending_signups.id;


--
-- Name: pending_social_signups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pending_social_signups (
    id bigint NOT NULL,
    token_hash character varying(255) NOT NULL,
    provider character varying(20) NOT NULL,
    provider_id character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    nickname character varying(100),
    redirect_path character varying(500) DEFAULT '/home'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    expires_at timestamp without time zone NOT NULL
);


--
-- Name: pending_social_signups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.pending_social_signups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pending_social_signups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.pending_social_signups_id_seq OWNED BY public.pending_social_signups.id;


--
-- Name: policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.policies (
    id bigint NOT NULL,
    slug character varying(160),
    title character varying(200) NOT NULL,
    organization character varying(100),
    policy_type character varying(30),
    description text,
    benefit_amount integer,
    benefit_detail text,
    target_condition text,
    region character varying(50) NOT NULL,
    start_date date,
    end_date date,
    official_url character varying(500),
    policy_comment character varying(300),
    policy_period character varying(100),
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    apply_url character varying(500),
    source_type character varying(50),
    source_name character varying(100),
    source_category character varying(80),
    external_source_record_id bigint,
    source_url character varying(500),
    source_canonical_key character varying(160),
    normalized_at timestamp without time zone,
    last_verified_at timestamp without time zone,
    verification_status character varying(30),
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    admin_override_enabled boolean DEFAULT false NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    structured_detail jsonb,
    city character varying(80),
    CONSTRAINT ck_policies_status_active_hidden CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'hidden'::character varying])::text[])))
);


--
-- Name: policies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: policies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.policies_id_seq OWNED BY public.policies.id;


--
-- Name: policy_collection_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.policy_collection_sources (
    id bigint NOT NULL,
    key character varying(80) NOT NULL,
    adapter_key character varying(80) NOT NULL,
    official_url character varying(500) NOT NULL,
    source_category character varying(80) NOT NULL,
    display_name character varying(120) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    publication_mode character varying(40) DEFAULT 'review'::character varying NOT NULL,
    expected_min_records integer DEFAULT 0 NOT NULL,
    last_outcome character varying(40),
    last_collected_at timestamp without time zone,
    last_successful_at timestamp without time zone,
    last_error text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    last_parsed_count integer,
    CONSTRAINT ck_policy_collection_sources_publication_mode CHECK (((publication_mode)::text = ANY ((ARRAY['review'::character varying, 'auto_after_reviewed_baseline'::character varying])::text[])))
);


--
-- Name: policy_collection_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.policy_collection_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: policy_collection_sources_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.policy_collection_sources_id_seq OWNED BY public.policy_collection_sources.id;


--
-- Name: policy_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.policy_documents (
    id bigint NOT NULL,
    policy_id bigint NOT NULL,
    document_name character varying(100) NOT NULL,
    description character varying(255),
    is_required boolean DEFAULT true NOT NULL
);


--
-- Name: policy_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.policy_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: policy_documents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.policy_documents_id_seq OWNED BY public.policy_documents.id;


--
-- Name: policy_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.policy_photos (
    id bigint NOT NULL,
    policy_id bigint NOT NULL,
    provider character varying(30) NOT NULL,
    provider_content_id character varying(60),
    image_url character varying(500) NOT NULL,
    thumbnail_url character varying(500),
    alt_text character varying(200) NOT NULL,
    attribution_text character varying(120) NOT NULL,
    relevance_score integer NOT NULL,
    assignment_reason character varying(30) NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    fetched_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    copyright_type character varying(20),
    image_width integer,
    image_height integer
);


--
-- Name: policy_photos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.policy_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: policy_photos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.policy_photos_id_seq OWNED BY public.policy_photos.id;


--
-- Name: policy_review_candidates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.policy_review_candidates (
    id bigint NOT NULL,
    external_source_record_id bigint NOT NULL,
    review_status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    change_kind character varying(20) NOT NULL,
    evidence_fingerprint character varying(64) NOT NULL,
    reviewed_by_user_id bigint,
    reviewed_at timestamp without time zone,
    review_note text,
    published_policy_id bigint,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    review_reason character varying(40),
    CONSTRAINT ck_policy_review_candidates_change_kind CHECK (((change_kind)::text = ANY ((ARRAY['new'::character varying, 'material_change'::character varying])::text[]))),
    CONSTRAINT ck_policy_review_candidates_review_status CHECK (((review_status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'superseded'::character varying])::text[])))
);


--
-- Name: policy_review_candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.policy_review_candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: policy_review_candidates_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.policy_review_candidates_id_seq OWNED BY public.policy_review_candidates.id;


--
-- Name: recommendations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendations (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    trip_id bigint,
    query text,
    result jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: recommendations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.recommendations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: recommendations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.recommendations_id_seq OWNED BY public.recommendations.id;


--
-- Name: region_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.region_photos (
    id bigint NOT NULL,
    provider character varying(30) NOT NULL,
    sido character varying(50) NOT NULL,
    city character varying(80) DEFAULT ''::character varying NOT NULL,
    provider_content_id character varying(60),
    content_title character varying(200),
    hero_image_url character varying(500),
    thumb_image_url character varying(500),
    provider_image_url character varying(500),
    storage_kind character varying(20) DEFAULT 'remote'::character varying NOT NULL,
    attribution_text character varying(120) DEFAULT '사진: 한국관광공사'::character varying NOT NULL,
    status character varying(20) DEFAULT 'active'::character varying NOT NULL,
    fetched_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    copyright_type character varying(20),
    image_width integer,
    image_height integer,
    selection_reason character varying(30)
);


--
-- Name: region_photos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.region_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: region_photos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.region_photos_id_seq OWNED BY public.region_photos.id;


--
-- Name: social_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.social_accounts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    provider_id character varying(255) NOT NULL,
    provider_nickname character varying(100),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: social_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.social_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: social_accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.social_accounts_id_seq OWNED BY public.social_accounts.id;


--
-- Name: trip_days; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_days (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    day_number integer NOT NULL,
    date date NOT NULL
);


--
-- Name: trip_days_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_days_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_days_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_days_id_seq OWNED BY public.trip_days.id;


--
-- Name: trip_invites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_invites (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    invite_token character varying(100) NOT NULL,
    created_by bigint NOT NULL,
    accepted_at timestamp without time zone,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    role character varying(20) DEFAULT 'editor'::character varying NOT NULL
);


--
-- Name: trip_invites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_invites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_invites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_invites_id_seq OWNED BY public.trip_invites.id;


--
-- Name: trip_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_members (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role character varying(20) DEFAULT 'editor'::character varying NOT NULL,
    joined_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: trip_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_members_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_members_id_seq OWNED BY public.trip_members.id;


--
-- Name: trip_places; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_places (
    id bigint NOT NULL,
    trip_day_id bigint NOT NULL,
    place_name character varying(200) NOT NULL,
    address character varying(500),
    latitude numeric(10,7),
    longitude numeric(10,7),
    visit_time time without time zone,
    order_num integer,
    memo text,
    source_provider character varying(40),
    external_place_id character varying(80),
    category_group_code character varying(20),
    category_group_name character varying(80),
    place_url character varying(500)
);


--
-- Name: trip_places_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_places_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_places_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_places_id_seq OWNED BY public.trip_places.id;


--
-- Name: trip_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_policies (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    policy_id bigint NOT NULL,
    added_at timestamp without time zone DEFAULT now() NOT NULL,
    application_status character varying(24),
    application_checklist jsonb,
    application_updated_at timestamp without time zone,
    application_updated_by_user_id bigint,
    CONSTRAINT ck_trip_policies_application_status CHECK (((application_status IS NULL) OR ((application_status)::text = ANY ((ARRAY['not_started'::character varying, 'applied'::character varying, 'selected'::character varying, 'not_selected'::character varying, 'traveled'::character varying, 'documents_submitted'::character varying, 'paid'::character varying])::text[]))))
);


--
-- Name: trip_policies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trip_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trip_policies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trip_policies_id_seq OWNED BY public.trip_policies.id;


--
-- Name: trips; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trips (
    id bigint NOT NULL,
    owner_id bigint NOT NULL,
    title character varying(200) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    region character varying(100),
    description text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    status character varying(20) DEFAULT 'draft'::character varying NOT NULL,
    travel_area_id character varying(120),
    participant_count integer DEFAULT 1 NOT NULL,
    revision integer DEFAULT 1 NOT NULL
);


--
-- Name: trips_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trips_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trips_id_seq OWNED BY public.trips.id;


--
-- Name: user_saved_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_saved_policies (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    policy_id bigint NOT NULL,
    saved_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: user_saved_policies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_saved_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_saved_policies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_saved_policies_id_seq OWNED BY public.user_saved_policies.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255),
    nickname character varying(50) NOT NULL,
    preferred_regions character varying(255),
    onboarding_completed boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    travel_style character varying(50),
    travel_budget character varying(50),
    role character varying(20) DEFAULT 'user'::character varying NOT NULL,
    nickname_setup_completed boolean DEFAULT true NOT NULL,
    profile_setup_skipped boolean DEFAULT false NOT NULL,
    terms_accepted boolean DEFAULT false NOT NULL,
    terms_accepted_at timestamp without time zone,
    terms_version character varying(32),
    privacy_accepted boolean DEFAULT false NOT NULL,
    privacy_accepted_at timestamp without time zone,
    privacy_version character varying(32),
    withdrawn_at timestamp without time zone,
    withdrawn_email_hash character varying(64),
    CONSTRAINT ck_users_role_user_admin CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'admin'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: auth_refresh_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_refresh_tokens ALTER COLUMN id SET DEFAULT nextval('public.auth_refresh_tokens_id_seq'::regclass);


--
-- Name: eligible_island_catalog_snapshots id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_catalog_snapshots ALTER COLUMN id SET DEFAULT nextval('public.eligible_island_catalog_snapshots_id_seq'::regclass);


--
-- Name: eligible_island_catalogs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_catalogs ALTER COLUMN id SET DEFAULT nextval('public.eligible_island_catalogs_id_seq'::regclass);


--
-- Name: eligible_island_snapshot_entries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_snapshot_entries ALTER COLUMN id SET DEFAULT nextval('public.eligible_island_snapshot_entries_id_seq'::regclass);


--
-- Name: eligible_islands id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_islands ALTER COLUMN id SET DEFAULT nextval('public.eligible_islands_id_seq'::regclass);


--
-- Name: external_source_records id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_source_records ALTER COLUMN id SET DEFAULT nextval('public.external_source_records_id_seq'::regclass);


--
-- Name: notification_deliveries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_deliveries ALTER COLUMN id SET DEFAULT nextval('public.notification_deliveries_id_seq'::regclass);


--
-- Name: password_reset_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens ALTER COLUMN id SET DEFAULT nextval('public.password_reset_tokens_id_seq'::regclass);


--
-- Name: pending_signups id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_signups ALTER COLUMN id SET DEFAULT nextval('public.pending_signups_id_seq'::regclass);


--
-- Name: pending_social_signups id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_social_signups ALTER COLUMN id SET DEFAULT nextval('public.pending_social_signups_id_seq'::regclass);


--
-- Name: policies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policies ALTER COLUMN id SET DEFAULT nextval('public.policies_id_seq'::regclass);


--
-- Name: policy_collection_sources id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_collection_sources ALTER COLUMN id SET DEFAULT nextval('public.policy_collection_sources_id_seq'::regclass);


--
-- Name: policy_documents id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_documents ALTER COLUMN id SET DEFAULT nextval('public.policy_documents_id_seq'::regclass);


--
-- Name: policy_photos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_photos ALTER COLUMN id SET DEFAULT nextval('public.policy_photos_id_seq'::regclass);


--
-- Name: policy_review_candidates id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_review_candidates ALTER COLUMN id SET DEFAULT nextval('public.policy_review_candidates_id_seq'::regclass);


--
-- Name: recommendations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations ALTER COLUMN id SET DEFAULT nextval('public.recommendations_id_seq'::regclass);


--
-- Name: region_photos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_photos ALTER COLUMN id SET DEFAULT nextval('public.region_photos_id_seq'::regclass);


--
-- Name: social_accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts ALTER COLUMN id SET DEFAULT nextval('public.social_accounts_id_seq'::regclass);


--
-- Name: trip_days id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_days ALTER COLUMN id SET DEFAULT nextval('public.trip_days_id_seq'::regclass);


--
-- Name: trip_invites id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_invites ALTER COLUMN id SET DEFAULT nextval('public.trip_invites_id_seq'::regclass);


--
-- Name: trip_members id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members ALTER COLUMN id SET DEFAULT nextval('public.trip_members_id_seq'::regclass);


--
-- Name: trip_places id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_places ALTER COLUMN id SET DEFAULT nextval('public.trip_places_id_seq'::regclass);


--
-- Name: trip_policies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_policies ALTER COLUMN id SET DEFAULT nextval('public.trip_policies_id_seq'::regclass);


--
-- Name: trips id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips ALTER COLUMN id SET DEFAULT nextval('public.trips_id_seq'::regclass);


--
-- Name: user_saved_policies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_saved_policies ALTER COLUMN id SET DEFAULT nextval('public.user_saved_policies_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: admin_audit_logs admin_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit_logs
    ADD CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: auth_refresh_tokens auth_refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_refresh_tokens
    ADD CONSTRAINT auth_refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: eligible_island_catalog_snapshots eligible_island_catalog_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_catalog_snapshots
    ADD CONSTRAINT eligible_island_catalog_snapshots_pkey PRIMARY KEY (id);


--
-- Name: eligible_island_catalogs eligible_island_catalogs_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_catalogs
    ADD CONSTRAINT eligible_island_catalogs_key_key UNIQUE (key);


--
-- Name: eligible_island_catalogs eligible_island_catalogs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_catalogs
    ADD CONSTRAINT eligible_island_catalogs_pkey PRIMARY KEY (id);


--
-- Name: eligible_island_snapshot_entries eligible_island_snapshot_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_snapshot_entries
    ADD CONSTRAINT eligible_island_snapshot_entries_pkey PRIMARY KEY (id);


--
-- Name: eligible_islands eligible_islands_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_islands
    ADD CONSTRAINT eligible_islands_pkey PRIMARY KEY (id);


--
-- Name: external_source_records external_source_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_source_records
    ADD CONSTRAINT external_source_records_pkey PRIMARY KEY (id);


--
-- Name: external_source_records external_source_records_source_name_source_category_canonic_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.external_source_records
    ADD CONSTRAINT external_source_records_source_name_source_category_canonic_key UNIQUE (source_name, source_category, canonical_key);


--
-- Name: notification_deliveries notification_deliveries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_deliveries
    ADD CONSTRAINT notification_deliveries_pkey PRIMARY KEY (id);


--
-- Name: notification_deliveries notification_deliveries_user_id_policy_id_channel_lead_day__key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_deliveries
    ADD CONSTRAINT notification_deliveries_user_id_policy_id_channel_lead_day__key UNIQUE (user_id, policy_id, channel, lead_day, target_deadline_date);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: pending_signups pending_signups_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_signups
    ADD CONSTRAINT pending_signups_email_key UNIQUE (email);


--
-- Name: pending_signups pending_signups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_signups
    ADD CONSTRAINT pending_signups_pkey PRIMARY KEY (id);


--
-- Name: pending_signups pending_signups_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_signups
    ADD CONSTRAINT pending_signups_token_hash_key UNIQUE (token_hash);


--
-- Name: pending_social_signups pending_social_signups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_social_signups
    ADD CONSTRAINT pending_social_signups_pkey PRIMARY KEY (id);


--
-- Name: pending_social_signups pending_social_signups_provider_provider_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_social_signups
    ADD CONSTRAINT pending_social_signups_provider_provider_id_key UNIQUE (provider, provider_id);


--
-- Name: pending_social_signups pending_social_signups_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_social_signups
    ADD CONSTRAINT pending_social_signups_token_hash_key UNIQUE (token_hash);


--
-- Name: policies policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policies
    ADD CONSTRAINT policies_pkey PRIMARY KEY (id);


--
-- Name: policies policies_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policies
    ADD CONSTRAINT policies_slug_key UNIQUE (slug);


--
-- Name: policy_collection_sources policy_collection_sources_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_collection_sources
    ADD CONSTRAINT policy_collection_sources_key_key UNIQUE (key);


--
-- Name: policy_collection_sources policy_collection_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_collection_sources
    ADD CONSTRAINT policy_collection_sources_pkey PRIMARY KEY (id);


--
-- Name: policy_documents policy_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_documents
    ADD CONSTRAINT policy_documents_pkey PRIMARY KEY (id);


--
-- Name: policy_photos policy_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_photos
    ADD CONSTRAINT policy_photos_pkey PRIMARY KEY (id);


--
-- Name: policy_photos policy_photos_policy_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_photos
    ADD CONSTRAINT policy_photos_policy_id_key UNIQUE (policy_id);


--
-- Name: policy_review_candidates policy_review_candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_review_candidates
    ADD CONSTRAINT policy_review_candidates_pkey PRIMARY KEY (id);


--
-- Name: recommendations recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT recommendations_pkey PRIMARY KEY (id);


--
-- Name: region_photos region_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_photos
    ADD CONSTRAINT region_photos_pkey PRIMARY KEY (id);


--
-- Name: region_photos region_photos_provider_sido_city_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.region_photos
    ADD CONSTRAINT region_photos_provider_sido_city_key UNIQUE (provider, sido, city);


--
-- Name: social_accounts social_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_pkey PRIMARY KEY (id);


--
-- Name: social_accounts social_accounts_provider_provider_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_provider_provider_id_key UNIQUE (provider, provider_id);


--
-- Name: trip_days trip_days_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_days
    ADD CONSTRAINT trip_days_pkey PRIMARY KEY (id);


--
-- Name: trip_days trip_days_trip_id_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_days
    ADD CONSTRAINT trip_days_trip_id_date_key UNIQUE (trip_id, date);


--
-- Name: trip_days trip_days_trip_id_day_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_days
    ADD CONSTRAINT trip_days_trip_id_day_number_key UNIQUE (trip_id, day_number);


--
-- Name: trip_invites trip_invites_invite_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_invites
    ADD CONSTRAINT trip_invites_invite_token_key UNIQUE (invite_token);


--
-- Name: trip_invites trip_invites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_invites
    ADD CONSTRAINT trip_invites_pkey PRIMARY KEY (id);


--
-- Name: trip_members trip_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members
    ADD CONSTRAINT trip_members_pkey PRIMARY KEY (id);


--
-- Name: trip_members trip_members_trip_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members
    ADD CONSTRAINT trip_members_trip_id_user_id_key UNIQUE (trip_id, user_id);


--
-- Name: trip_places trip_places_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_places
    ADD CONSTRAINT trip_places_pkey PRIMARY KEY (id);


--
-- Name: trip_policies trip_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_policies
    ADD CONSTRAINT trip_policies_pkey PRIMARY KEY (id);


--
-- Name: trip_policies trip_policies_trip_id_policy_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_policies
    ADD CONSTRAINT trip_policies_trip_id_policy_id_key UNIQUE (trip_id, policy_id);


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);


--
-- Name: eligible_island_snapshot_entries uq_eligible_island_snapshot_entries_snapshot_name_jurisdiction; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_snapshot_entries
    ADD CONSTRAINT uq_eligible_island_snapshot_entries_snapshot_name_jurisdiction UNIQUE (snapshot_id, normalized_name, jurisdiction_name);


--
-- Name: eligible_islands uq_eligible_islands_catalog_name_jurisdiction; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_islands
    ADD CONSTRAINT uq_eligible_islands_catalog_name_jurisdiction UNIQUE (catalog_id, normalized_name, jurisdiction_name);


--
-- Name: user_saved_policies user_saved_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_saved_policies
    ADD CONSTRAINT user_saved_policies_pkey PRIMARY KEY (id);


--
-- Name: user_saved_policies user_saved_policies_user_id_policy_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_saved_policies
    ADD CONSTRAINT user_saved_policies_user_id_policy_id_key UNIQUE (user_id, policy_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_auth_refresh_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_refresh_tokens_user_id ON public.auth_refresh_tokens USING btree (user_id);


--
-- Name: idx_policies_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_policies_slug ON public.policies USING btree (slug);


--
-- Name: idx_trip_invites_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trip_invites_token ON public.trip_invites USING btree (invite_token);


--
-- Name: idx_trip_invites_trip_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trip_invites_trip_id ON public.trip_invites USING btree (trip_id);


--
-- Name: ix_admin_audit_logs_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_admin_audit_logs_action ON public.admin_audit_logs USING btree (action);


--
-- Name: ix_admin_audit_logs_admin_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_admin_audit_logs_admin_user_id ON public.admin_audit_logs USING btree (admin_user_id);


--
-- Name: ix_admin_audit_logs_target_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_admin_audit_logs_target_id ON public.admin_audit_logs USING btree (target_id);


--
-- Name: ix_admin_audit_logs_target_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_admin_audit_logs_target_type ON public.admin_audit_logs USING btree (target_type);


--
-- Name: ix_eligible_island_catalog_snapshots_attachment_fingerprint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_eligible_island_catalog_snapshots_attachment_fingerprint ON public.eligible_island_catalog_snapshots USING btree (attachment_fingerprint);


--
-- Name: ix_eligible_island_catalog_snapshots_catalog_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_eligible_island_catalog_snapshots_catalog_id ON public.eligible_island_catalog_snapshots USING btree (catalog_id);


--
-- Name: ix_eligible_island_catalog_snapshots_reviewed_by_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_eligible_island_catalog_snapshots_reviewed_by_user_id ON public.eligible_island_catalog_snapshots USING btree (reviewed_by_user_id);


--
-- Name: ix_eligible_island_catalogs_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_eligible_island_catalogs_key ON public.eligible_island_catalogs USING btree (key);


--
-- Name: ix_eligible_island_snapshot_entries_snapshot_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_eligible_island_snapshot_entries_snapshot_id ON public.eligible_island_snapshot_entries USING btree (snapshot_id);


--
-- Name: ix_eligible_islands_catalog_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_eligible_islands_catalog_id ON public.eligible_islands USING btree (catalog_id);


--
-- Name: ix_eligible_islands_normalized_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_eligible_islands_normalized_name ON public.eligible_islands USING btree (normalized_name);


--
-- Name: ix_eligible_islands_snapshot_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_eligible_islands_snapshot_id ON public.eligible_islands USING btree (snapshot_id);


--
-- Name: ix_external_source_records_canonical_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_external_source_records_canonical_key ON public.external_source_records USING btree (canonical_key);


--
-- Name: ix_external_source_records_end_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_external_source_records_end_date ON public.external_source_records USING btree (end_date);


--
-- Name: ix_external_source_records_external_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_external_source_records_external_id ON public.external_source_records USING btree (external_id);


--
-- Name: ix_external_source_records_logical_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_external_source_records_logical_key ON public.external_source_records USING btree (logical_key);


--
-- Name: ix_external_source_records_region; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_external_source_records_region ON public.external_source_records USING btree (region);


--
-- Name: ix_external_source_records_source_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_external_source_records_source_category ON public.external_source_records USING btree (source_category);


--
-- Name: ix_external_source_records_source_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_external_source_records_source_name ON public.external_source_records USING btree (source_name);


--
-- Name: ix_external_source_records_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_external_source_records_status ON public.external_source_records USING btree (status);


--
-- Name: ix_notification_deliveries_policy_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notification_deliveries_policy_id ON public.notification_deliveries USING btree (policy_id);


--
-- Name: ix_notification_deliveries_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notification_deliveries_user_id ON public.notification_deliveries USING btree (user_id);


--
-- Name: ix_password_reset_tokens_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_password_reset_tokens_token_hash ON public.password_reset_tokens USING btree (token_hash);


--
-- Name: ix_password_reset_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_password_reset_tokens_user_id ON public.password_reset_tokens USING btree (user_id);


--
-- Name: ix_pending_signups_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pending_signups_email ON public.pending_signups USING btree (email);


--
-- Name: ix_pending_signups_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pending_signups_token_hash ON public.pending_signups USING btree (token_hash);


--
-- Name: ix_pending_social_signups_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pending_social_signups_token_hash ON public.pending_social_signups USING btree (token_hash);


--
-- Name: ix_policies_external_source_record_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policies_external_source_record_id ON public.policies USING btree (external_source_record_id);


--
-- Name: ix_policies_source_canonical_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policies_source_canonical_key ON public.policies USING btree (source_canonical_key);


--
-- Name: ix_policies_source_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policies_source_category ON public.policies USING btree (source_category);


--
-- Name: ix_policies_source_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policies_source_name ON public.policies USING btree (source_name);


--
-- Name: ix_policies_source_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policies_source_type ON public.policies USING btree (source_type);


--
-- Name: ix_policy_collection_sources_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policy_collection_sources_key ON public.policy_collection_sources USING btree (key);


--
-- Name: ix_policy_collection_sources_source_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policy_collection_sources_source_category ON public.policy_collection_sources USING btree (source_category);


--
-- Name: ix_policy_review_candidates_external_source_record_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policy_review_candidates_external_source_record_id ON public.policy_review_candidates USING btree (external_source_record_id);


--
-- Name: ix_policy_review_candidates_published_policy_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policy_review_candidates_published_policy_id ON public.policy_review_candidates USING btree (published_policy_id);


--
-- Name: ix_policy_review_candidates_reviewed_by_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_policy_review_candidates_reviewed_by_user_id ON public.policy_review_candidates USING btree (reviewed_by_user_id);


--
-- Name: ix_trip_places_external_place_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_trip_places_external_place_id ON public.trip_places USING btree (external_place_id);


--
-- Name: ix_trips_travel_area_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_trips_travel_area_id ON public.trips USING btree (travel_area_id);


--
-- Name: ix_user_saved_policies_policy_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_saved_policies_policy_id ON public.user_saved_policies USING btree (policy_id);


--
-- Name: ix_user_saved_policies_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_user_saved_policies_user_id ON public.user_saved_policies USING btree (user_id);


--
-- Name: ix_users_withdrawn_email_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_users_withdrawn_email_hash ON public.users USING btree (withdrawn_email_hash);


--
-- Name: admin_audit_logs admin_audit_logs_admin_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit_logs
    ADD CONSTRAINT admin_audit_logs_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.users(id);


--
-- Name: auth_refresh_tokens auth_refresh_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_refresh_tokens
    ADD CONSTRAINT auth_refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: eligible_island_catalog_snapshots eligible_island_catalog_snapshots_catalog_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_catalog_snapshots
    ADD CONSTRAINT eligible_island_catalog_snapshots_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.eligible_island_catalogs(id) ON DELETE CASCADE;


--
-- Name: eligible_island_catalog_snapshots eligible_island_catalog_snapshots_reviewed_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_catalog_snapshots
    ADD CONSTRAINT eligible_island_catalog_snapshots_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: eligible_island_snapshot_entries eligible_island_snapshot_entries_snapshot_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_island_snapshot_entries
    ADD CONSTRAINT eligible_island_snapshot_entries_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES public.eligible_island_catalog_snapshots(id) ON DELETE CASCADE;


--
-- Name: eligible_islands eligible_islands_catalog_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_islands
    ADD CONSTRAINT eligible_islands_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.eligible_island_catalogs(id) ON DELETE CASCADE;


--
-- Name: eligible_islands eligible_islands_snapshot_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.eligible_islands
    ADD CONSTRAINT eligible_islands_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES public.eligible_island_catalog_snapshots(id) ON DELETE CASCADE;


--
-- Name: policies fk_policies_external_source_record_id_external_source_records; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policies
    ADD CONSTRAINT fk_policies_external_source_record_id_external_source_records FOREIGN KEY (external_source_record_id) REFERENCES public.external_source_records(id) ON DELETE SET NULL;


--
-- Name: trip_policies fk_trip_policies_application_updated_by_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_policies
    ADD CONSTRAINT fk_trip_policies_application_updated_by_user_id FOREIGN KEY (application_updated_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: notification_deliveries notification_deliveries_policy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_deliveries
    ADD CONSTRAINT notification_deliveries_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id);


--
-- Name: notification_deliveries notification_deliveries_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_deliveries
    ADD CONSTRAINT notification_deliveries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: password_reset_tokens password_reset_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: policy_documents policy_documents_policy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_documents
    ADD CONSTRAINT policy_documents_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id) ON DELETE CASCADE;


--
-- Name: policy_photos policy_photos_policy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_photos
    ADD CONSTRAINT policy_photos_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id) ON DELETE CASCADE;


--
-- Name: policy_review_candidates policy_review_candidates_external_source_record_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_review_candidates
    ADD CONSTRAINT policy_review_candidates_external_source_record_id_fkey FOREIGN KEY (external_source_record_id) REFERENCES public.external_source_records(id) ON DELETE CASCADE;


--
-- Name: policy_review_candidates policy_review_candidates_published_policy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_review_candidates
    ADD CONSTRAINT policy_review_candidates_published_policy_id_fkey FOREIGN KEY (published_policy_id) REFERENCES public.policies(id) ON DELETE SET NULL;


--
-- Name: policy_review_candidates policy_review_candidates_reviewed_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_review_candidates
    ADD CONSTRAINT policy_review_candidates_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: recommendations recommendations_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT recommendations_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: recommendations recommendations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: social_accounts social_accounts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: trip_days trip_days_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_days
    ADD CONSTRAINT trip_days_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE CASCADE;


--
-- Name: trip_invites trip_invites_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_invites
    ADD CONSTRAINT trip_invites_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: trip_invites trip_invites_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_invites
    ADD CONSTRAINT trip_invites_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE CASCADE;


--
-- Name: trip_members trip_members_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members
    ADD CONSTRAINT trip_members_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE CASCADE;


--
-- Name: trip_members trip_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_members
    ADD CONSTRAINT trip_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: trip_places trip_places_trip_day_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_places
    ADD CONSTRAINT trip_places_trip_day_id_fkey FOREIGN KEY (trip_day_id) REFERENCES public.trip_days(id) ON DELETE CASCADE;


--
-- Name: trip_policies trip_policies_policy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_policies
    ADD CONSTRAINT trip_policies_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id);


--
-- Name: trip_policies trip_policies_trip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_policies
    ADD CONSTRAINT trip_policies_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE CASCADE;


--
-- Name: trips trips_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: user_saved_policies user_saved_policies_policy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_saved_policies
    ADD CONSTRAINT user_saved_policies_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id);


--
-- Name: user_saved_policies user_saved_policies_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_saved_policies
    ADD CONSTRAINT user_saved_policies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict u9vh52NFMlhXUqWIE006EOsvFqGhpGU23DDV7Lyg7sckDU2O9EFZLhdsMqRT7xv
